# Smart Contract Configuration for Base Mainnet
contracts:
  - name: "UNISWAP_V3_ROUTER"
    address: "0x2626664c2603336E57B271c5C0b26F421741e481"
    abi_path: "abi/uniswap_v3_router.json"

  - name: "UNISWAP_UNIVERSAL_ROUTER"
    address: "0x3fC91A3afd70395Cd496C647d5a6CC9D4B2b7FAD"
    abi_path: "abi/uniswap_universal_router.json"

  - name: "UNISWAP_V3_QUOTER"
    address: "0x3d4e44Eb1374240CE5F1B871ab261CD16335B76a"
    abi_path: "abi/uniswap_v3_quoter.json"