# ROOK Agent Configuration: ETH/USDC Trading Pair
# This configuration defines a specialized ROOK agent for ETH/USDC trading

agent:
  name: "rook_eth_usdc"
  pair: "ETH/USDC"
  pool_id: "0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640"  # ETH/USDC 0.05% pool
  fee_tier: 0.0005  # 0.05%

# Model configuration
model:
  name: "fin-r1"
  provider: "transformers"  # Options: ollama, openrouter, transformers
  adapter_path: "./models/adapters/rook/ETH_USDC/lora.safetensors"

# Alternative model configurations
# model:
#   name: "deepseek-r1-distill-llama-70b"
#   provider: "ollama"
#   adapter_path: null

# Portfolio settings
portfolio:
  target_allocation: 0.5  # 50% ETH, 50% USDC
  initial_eth_balance: 1.0
  initial_usdc_balance: 4300.0

# Risk management
risk:
  max_slippage: 0.03  # 3% maximum slippage
  max_position_size: 0.1  # 10% of portfolio per trade
  max_daily_trades: 50
  min_confidence: 0.3  # Minimum confidence for trade execution
  max_drawdown_threshold: 0.2  # 20% maximum drawdown

# Execution settings
execution:
  default_slippage: 0.005  # 0.5% default slippage
  default_deadline: 20  # 20 minutes
  min_trade_size: 0.001  # 0.001 ETH minimum

# Monitoring and logging
monitoring:
  enable_metrics: true
  log_level: "INFO"
  save_state_interval: 300  # Save state every 5 minutes
  performance_report_interval: 600  # Report every 10 minutes

# Network configuration
network:
  rpc_url: "https://mainnet.base.org"
  ws_url: "wss://mainnet.base.org"
  chain_id: 8453

# Market data
market_data:
  price_feed: "coingecko"  # Options: coingecko, chainlink, uniswap
  update_interval: 30  # seconds
  volatility_window: 600  # 10 minutes for volatility calculation